### ISSUE TITLE
Using custom detection

### ISSUE THREAD

**Issue by blondski** [erksch/3D-object-tracking#1]
I want to integrate this project into a traffic analytics university project. We use OpenPCDet with a model trained on the Waymo dataset in our work. Given that we have the boxes and their labels, how would I have to change your code to work with those detections? Thanks
@erksch

**Comment by erksch** [comment]
The code works directly on the ground truths from the waymo dataset. 
But you can probably construct a better interface and use your predictions.

**Comment by blondski** [comment]
Alright. By the way, I encountered some errors while testing current code, e.g (`dropout` argument dest set to "n_frames" causing arg not found error / PredictiveTracker.py line 45 :
         removed_idx = []\
        i = len(self.trackers)\
        for tracker in reversed(self.trackers):\
            i -= 1\
            if tracker.blind_time >= self.max_age:\
                self.trackers.pop(i)\
                removed_idx.append(str(self.trackers[i].id))\
will yield out-of-bound error if i==len(self.trackers)

**Comment by blondski** [comment]
Also, could you provide a brief explanation on interpreting this output? Much appreciated!
![image](https://user-images.githubusercontent.com/57535992/170025390-29fe898b-9668-402a-8e85-4fc65962f5fd.png)

**Comment by erksch** [comment]
I fixed the dropout argument, sorry about that.

Maybe as a side note, this repository is just some random seminar project of mine with poor documentation. For example, you should not use the dropout argument, it drops predictions from frames to test the trackers more thoroughly because the ground truths in the waymo dataset are too good to actually see a difference between the tracker implementations.

The first output shows the tracked objects over the frames. The last one shows a comparison between the ground truth trajectories and the predicted ones (red are misses and blue are mismatches). You will see that without dropout the trackers will work really well.

**Comment by blondski** [comment]
no biggie on the errors; But I'm interested in tracking both for object ID-ing and halving the number of frames processed by the detectors (i.e. evaluate every-other frame and compensate with the tracker)  - the question is - could it perform in real-time given that we start with a pair of detections (i.e. frame 1 & 2) and the hypothesis are generated based on each new frame 
?

**Comment by erksch** [comment]
The 3D IoU calculation is probably the most resource-intensive part. I implemented it via tensor operations so it should run on a GPU and be very fast. I think you just have to try it out.

**Comment by blondski** [comment]
For some reason, even with 0 drop-outs the number of predictive objects can be 7x times greater than real objects (in some cases). Am I misinterpreting something in the logged output? @erksch
